/*
 * Created on Dec 15, 2004 at 10:56:29 PM.
 */
package uk.ac.standrews.cs.util;

import org.junit.Test;
import uk.ac.standrews.cs.interfaces.IKey;

import java.net.InetSocketAddress;

import static org.junit.Assert.*;

/**
 * Test class for KeyFactory.
 *
 * @author graham
 * @author sic2 - added tests for recreateKey()
 */
public class KeyFactoryTest {

    /*
     * Class under test for Key generateKey()
     */
    @Test
    public void testGenerateKey() {
        
        IKey k1 = SHA1KeyFactory.generateKey();
        IKey k2 = SHA1KeyFactory.generateKey();
    	
        // Key generated by SHA1 from string "null".
        assertEquals("2be88ca4242c76e8253ac62474851065032d6833", k1.toString());

        // Subsequent calls should return equal but non-identical keys.
        assertNotSame(k1, k2);
        assertEquals(0, k1.compareTo(k2));
    }

    /*
     * Class under test for Key generateKey(String)
     */
    @Test
    public void testGenerateKeyWithString() {
        
        IKey k1 = SHA1KeyFactory.generateKey("null");
        IKey k2 = SHA1KeyFactory.generateKey("quick brown fox");
        IKey k3 = SHA1KeyFactory.generateKey("quick brown fox");
    	
        // Key generated by SHA1 from string "null".
        assertEquals("2be88ca4242c76e8253ac62474851065032d6833", k1.toString());

        // Key generated by SHA1 from string "quick brown fox".
        assertEquals("a9762606f9e33e452f06b4562e253efb6038b512", k2.toString());
        
        // Subsequent calls should return equal keys.
        assertEquals(0, k2.compareTo(k3));
        assertNotEquals(0, k1.compareTo(k2));
    }

    /*
     * Class under test for Key generateKey(INetSocketAddress)
     */
    @Test
    public void testGenerateKeyWithIPAddress() {
        IKey k1 = SHA1KeyFactory.generateKey(new InetSocketAddress("138.251.195.25", 80));
        IKey k2 = SHA1KeyFactory.generateKey(new InetSocketAddress("212.58.224.56", 1024));

        // Keys generated by SHA1 from addresses above.
        assertEquals("195e24370036a4062b0d325c03153a2b9fc9c92e", k1.toString());
        assertEquals("6280b63d4e1f488235bce11c30c6d3130141fc07", k2.toString());
    }

    @Test
    public void testRecreateKey() {
        IKey k1 = SHA1KeyFactory.recreateKey("195e24370036a4062b0d325c03153a2b9fc9c92e");
        assertEquals("195e24370036a4062b0d325c03153a2b9fc9c92e", k1.toString());
    }

    @Test
    public void testRecreateKeyOverflow() {
        IKey k1 = SHA1KeyFactory.recreateKey("195e24370036a4062b0d325c03153a2b9fc9c92e1");
        assertEquals("95e24370036a4062b0d325c03153a2b9fc9c92e1", k1.toString());
    }

    @Test
    public void testRecreateKeyUpperCase() {
        IKey k1 = SHA1KeyFactory.recreateKey("195E24370036A4062B0D325C03153A2B9FC9C92E");
        assertEquals("195e24370036a4062b0d325c03153a2b9fc9c92e", k1.toString());
    }

    @Test (expected = NullPointerException.class)
    public void testRecreateKeyNull() {
        IKey k1 = SHA1KeyFactory.recreateKey(null);
        assertEquals("195e24370036a4062b0d325c03153a2b9fc9c92e", k1.toString());
    }

    @Test (expected = NumberFormatException.class)
    public void testRecreateKeyEmpty() {
        IKey k1 = SHA1KeyFactory.recreateKey("");
        assertEquals("195e24370036a4062b0d325c03153a2b9fc9c92e", k1.toString());
    }
}
